const payload = {
  siteId: "63bd5deeb0d2be7871f4dc8b", userId: "63af057c67bbed344772810b",
  accessKey: "AKIAQLLHWD6MLGLBOVQW",
  allowAdvancedPublish: false,
  allowCustomCode: false,
  allowDocumentUploads: false,
  allowExport: false,
  allowFormFileUpload: false,
  allowPasswordProtection: false,
  allowPublish: true,
  allowPublishDomain: false,
  allowScheduledSIP: false,
  allowSiteSearch: false,
  assetManagerFolders: [],
  baseInteractions: {_id: "64aee7aebf5b4d4360bae669", ix2: {events: [], actionLists: [], interactions: []}, syncCount: 0,…},
  baseStyles: {blocks: [], data: {}},
  betas: {useNewBillingSystem: true, useUserTaxCollection: true, activateUserTaxCollection: true,…},
  customFontFallbacks: {},,
  devlinkConfigs: null,
  domNodes: [{_id: "63bd5deeb0d2be5075f4dc90", type: "Body", tag: "body", classes: [],…},…],
  domNodesVersion: 59,
  ecommBusinessAddress: null,
  ecommCurrencySettings: null,
  ecommDefaultCurrency: null,
  ecommShippingZones: null,
  email: "lucasatwon@gmail.com",
  files: [{_id: "63c430ca2c404bc2a802a9e2", isHD: false, isFileUpload: false, variants: [],…}],
  firstName: "Dozie Lucas",
  flowTriggers: {},
  flows: [],
  googleFonts: [],
  googleMapsApiKey: null,
  hasLegacyAuth: false,
  hasUserMonetized: false,
  installedApps: [],
  installedMarketplaceResources: [],
  integrations: {figma: {clientId: "rTm2TNJFBhUJv99b5aO6UL"}, github: {clientId: "c0d0b84cef06e8f65d95"}},
  interactions: {_id: "63bd5deeb0d2be7871f4dc8b", ix2: {events: [], actionLists: [], interactions: []},…},
  interactionsVersion: 4,
  isCloneable: false,
  isOrg: false,
  isStagingPrivate: false,
  isUserInOrg: false,
  isUserServiceProvider: true,
  languageCode: null,
  lastName: "Imo",
  lastPublished: "2023-01-14T10:03:00.083Z",
  localization: {},
  marketplace: false,
  maxCollections: 20,
  maxEcomItems: 50,
  maxFields: 30,
  maxItemRefs: 5,
  maxItems: 50,
  maxLocales: 1,
  maxPages: 2,
  onboardingPersistentState: {eventCounters: {__contextual_prompt__symbol-tutorial-manually-triggered: 1,…},…},
  otherFonts: [],
  pageId: "63bd5deeb0d2be0101f4dc8f",
  pages: [{shouldPublish: true, _id: "63bd5deeb0d2be0101f4dc8f", parent: null, type: "page", utilKey: null,…},…]
  plan: "free",
  preferredUrl: "dozie-lucass-stunning-site.webflow.io",
  publishedFlows: [],
  publishingOptions: {beautifyHtml: false, uglifyCss: false, minifyJs: true, secureFrameHeaders: false, sslHosting: true}
  recaptchaRequired: false,
  responsiveImages: true,
  role: "developer",
  roles: {site: "project_admin", workspace: "owner"},
  s3bucket: "webflow-prod-assets",
  s3bucketDir: "63bd5deeb0d2be7871f4dc8b/",
  searchIndexPeriodAuto: 604800000,
  searchIndexPeriodManual: 604800000,
  secrets: {site: {site: "63bd5deeb0d2be7871f4dc8b", secret: true, sitePassword: false},…},
  serverTime: 1689184174231,
  siteBasePath: null,
  siteCss: "",
  siteId: "63bd5deeb0d2be7871f4dc8b",
  siteName: "Dozie Lucas's Stunning Site",
  sitePlugin: {values: [], componentForms: {}},
  siteProfileSlug: null,
  siteSubscription: {type: "free"},
  styles: {,…},
  stylesVersion: 35,
  symbolUsageMap: {},
  symbols: [],
  syncPatchedMeta: false,
  templateOf: null
  templateType: "Blank"
  timezone: "Africa/Lagos"
  tutorial: null
  typeKitApiKey: null
  typeKitFonts: []
  typeKitId: []
  userEmail: "lucasatwon@gmail.com"
  userId: "63af057c67bbed344772810b"
  version: 112
  visibleBackups: 2
  workspaceId: "63af057c67bbedffae72810d"
  workspaceSeatCount: 1
  workspaceSlug: "dozie-lucass-works"
}